name : Deploy the app

on:
    push:
        branches:
        - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name : Docker login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                file: docker/Dockerfile.prod
                push: true
                tags: kunalnasa/portfolio-image:${{ github.sha }}
                secrets: |
                    id=email_service_id,env=EMAIL_SERVICE_ID
                    id=email_template_id,env=EMAIL_TEMPLATE_ID
                    id=email_public_key,env=EMAIL_PUBLIC_KEY
              env:
                EMAIL_SERVICE_ID: ${{ secrets.EMAIL_SERVICE_ID }}
                EMAIL_TEMPLATE_ID: ${{ secrets.EMAIL_TEMPLATE_ID }}
                EMAIL_PUBLIC_KEY: ${{ secrets.EMAIL_PUBLIC_KEY }}


        
            